### ISSUE TITLE
High-minus (APL) combines with next character in notepad.exe

### ISSUE THREAD

**Issue by arcfide** [fabrizioschiavi/pragmatapro#117]
I just noticed a strange interaction with APL glyphs in some Windows editors. With Dyalog APL, the font renders slowly, but correctly (v 0.827) when putting  ¯2 in the code. However, with Notepad.exe, the high-minus seems to merge with the next letter, resulting in, for instance, a vertical bar over `a` if I juxtapose the high-minus with `a`. With numbers, because they are taller, the high-minus completely disappears.

**Comment by arcfide** [comment]
I have noticed that this is also happening with ¯1 in Microsoft word.

**Comment by fabrizioschiavi** [comment]
Fixed since 0.828 version. 
Unfortunately other users will be unable to see correctly characters like `Ā ā Ī ī…` to fix this issue

**Comment by arcfide** [comment]
I just downloaded 0.828 and tried this, but the issue is still there. With the Liga and non-Liga versions.

**Comment by fabrizioschiavi** [comment]
Sorry @arcfide but I see this in Notepad

![PragmataPro Notepad](https://user-images.githubusercontent.com/1576663/62452609-d9cfb880-b770-11e9-82cf-697563c0698e.png)


Isn't that what you wanted?

**Comment by arcfide** [comment]
I have attached what I see in the new version compared to the canonical font. The sample text is:


   ¯0 ¯1 ¯2 ¯3 ¯4 ¯5 ¯6 ¯7 ¯8 ¯9 ¯50 ¯32

   ⌽⍉⊖⍟⍥○*∘⍤⍣

   ¨¯<≤=≥>≠∨∧×÷⊢⋄
   ?⍵∊⍴~↑↓⍳○*←→
   ⍺⌈⌊_∇∆∘'⎕⍎⍕
   ⊂⊥⊤|⍝⍀⌿

   ⌶⍫⍒⍋⌽⍉⊖⍟⍱!⌹⊣⌺
   ⍷⍨⍸⍥⍣⍞⍬
   ⍺⍤⌸⌷≡≢
   ⊆⊃∩∪⍪⍙⍠

**Comment by arcfide** [comment]
I don't know what's going on, but I wanted to update you and report that this issue appears to be fixed for Pragmata Pro Liga and non-Liga forms, but not for Mono in 0.828 on the latest version of Microsoft Windows for Notepad. I don't know what has change, but I'm closing this issue as it does not appear to be a problem at this point. If it pops back up, I'll reopen.
